name: Update Data CI

on:
  repository_dispatch:
    types: [update-data]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: git config --global user.email "github-actions@example.com"
    - run: git config --global user.name "github-actions"
    - run: git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
    - run: git pull github ${GITHUB_REF} --ff-only
    - run: npm ci
    - run: npm run update-data
      env:
        X_API_KEY: ${{ secrets.X_API_KEY }}
    - run: git add .
    - run: git commit -m "update data"
    - run: git push origin HEAD